export const EVENT_TYPES = {
  RAW_IMPORT_CREATED: 'RAW_IMPORT_CREATED',
  IMPORT_APPROVED: 'IMPORT_APPROVED',
  IMPORT_REJECTED: 'IMPORT_REJECTED',
  INVENTORY_CREATED: 'INVENTORY_CREATED',
  QUOTE_CREATED: 'QUOTE_CREATED',
  QUOTE_LOCKED: 'QUOTE_LOCKED',
  BOOKING_CREATED: 'BOOKING_CREATED',
  BOOKING_CONFIRMED: 'BOOKING_CONFIRMED',
  PRICE_UPDATED: 'PRICE_UPDATED',
  KILL_SWITCH_TRIGGERED: 'KILL_SWITCH_TRIGGERED'
} as const;

export type EventType = keyof typeof EVENT_TYPES;
