export const BOOKING_STATES = {
  QUOTE_CREATED: 'QUOTE_CREATED',
  PRICE_LOCKED: 'PRICE_LOCKED',
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  PAYMENT_VERIFIED: 'PAYMENT_VERIFIED',
  BOOKING_CONFIRMED: 'BOOKING_CONFIRMED'
} as const;

export type BookingState = keyof typeof BOOKING_STATES;

export const ALLOWED_TRANSITIONS: Record<BookingState, BookingState[]> = {
  [BOOKING_STATES.QUOTE_CREATED]: [BOOKING_STATES.PRICE_LOCKED],
  [BOOKING_STATES.PRICE_LOCKED]: [BOOKING_STATES.PAYMENT_PENDING],
  [BOOKING_STATES.PAYMENT_PENDING]: [BOOKING_STATES.PAYMENT_VERIFIED],
  [BOOKING_STATES.PAYMENT_VERIFIED]: [BOOKING_STATES.BOOKING_CONFIRMED],
  [BOOKING_STATES.BOOKING_CONFIRMED]: [] // Terminal state
};
